### PR TITLE
February 2018 update

### PR DESCRIPTION
**Pull request by Subadai**
Hopefully done correctly...

### CODE REVIEW

**Comment by z16** [comment]
Something isn't quite right here... it marks every line as changed, almost as if the line ending was changed? Which I don't think should happen, since we use a StreamWriter, which doesn't mention depending on the environment, but still, did you run this on a non-Windows environment?

Please see if you can fix that on your end, in the meantime I'll update the resources for this update myself.

**Comment by Subadai** [comment]
I ran it on Windows 10. After I forked the repository, I uploaded the files produced by the extractor and made the pull request. I'm a git newb, so anything I should have done differently, let me know.

**Comment by Ninjistix** [comment]
kinda late to the pt, but it was prob the line ends or white space, because if you check https://github.com/Windower/Resources/pull/25/files?w=1 you can see its the same number of changes as the recent commit.

**Comment by z16** [comment]
Yeah, I just don't know *why* that would happen. The files are generated by our tool through a mechanism that, to my knowledge, does not vary in line endings.

**Pull request closed without merging**
